trigger:
  - main

pr: none

pool:
  name: "Default"

stages:
  - template: templates/stages/test-and-validate.yml
    parameters:
      environmentVariables:
        DUMMY_SECRET_KEY: "AKIA1234567890DUMMYKEY"
